spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/spring?serverTimezone=UTC
    username: root
    password: guoyangguoli123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
